spring:
  application:
    name: telconova-auth-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/telconova}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:root1}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    #hibernate:
    #  ddl-auto: create-drop
    # show-sql: true # Descomentar para mostrar las consultas SQL generadas
    # properties:
    #   hibernate.format_sql: true # Descomentar para formatear las consultas SQL
  
  security:
    user:
      name: ${ADMIN_USERNAME:admin}
      password: ${ADMIN_PASSWORD:admin123}

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    org.springframework.security: DEBUG

graphql:
  servlet:
    enabled: true
    mapping: /graphql

jwt:
  secret: ${JWT_SECRET}
  expiration_ms: ${JWT_EXPIRATION_MS}

swagger:
  production-server-url: ${SWAGGER_PRODUCTION_SERVER_URL}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
      cors:
        allowed-origins: "*"
        allowed-methods: GET
        
  endpoint:
    health:
      show-details: when-authorized
      probes:
        enabled: true
      group:
        readiness:
          include: readinessState,db
        liveness:
          include: livenessState,diskSpace
    prometheus:
      access: read-only  
    metrics:
      access: read-only  
      
  metrics:
    tags:
      application: auth-service
      service: telconova-supportsuite
      environment: ${spring.profiles.active:default}
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
      slo:
        "[http.server.requests]": 50ms,100ms,200ms,500ms,1s,2s
      percentiles:
        "[http.server.requests]": 0.5,0.95,0.99
    enable:
      jvm: true
      process: true
      system: true
      tomcat: true
      jdbc: true
  info:
    java:
      enabled: true
    env:
      enabled: true
    build:
      enabled: true
    os:
      enabled: true