spring:
  application:
    name: telconova-support-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/telconova
    username: postgres
    password: root1
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    #hibernate:
    #  ddl-auto: create-drop
    # show-sql: true # Descomentar para mostrar las consultas SQL generadas
    # properties:
    #   hibernate.format_sql: true # Descomentar para formatear las consultas SQL
  
  security:
    user:
      name: admin
      password: admin123

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
server:
  port: 8080

logging:
  level:
    org.springframework.security: DEBUG

graphql:
  servlet:
    enabled: true
    mapping: /graphql

jwt:
  secret: ${JWT_SECRET}
  expiration_ms: ${JWT_EXPIRATION_MS}

swagger:
  api:
    title: API de Gestión de Usuarios
    version: 1.0
    description: API para la gestión de usuarios y autenticacion
  terms-url: https://example.com/terms
  contact:
    name: Support Team
    email: support@example.com
    url: https://example.com/contact
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  production-server-url: ${SWAGGER_PRODUCTION_SERVER_URL}
  staging-server-url: https://staging-api.example.com